apiVersion: v1
kind: Service
metadata:
  name: backend-metrics
  namespace: prod
  labels:
    app: backend
    metrics: enabled
spec:
  selector:
    app: backend
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090

