apiVersion: v1
kind: Service
metadata:
  name: postgres-metrics
  namespace: prod
  labels:
    app: postgres
    metrics: enabled
spec:
  selector:
    app: postgres
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187

