apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway-metrics
  namespace: nginx-gateway
  labels:
    app.kubernetes.io/component: controller
    metrics: enabled
spec:
  selector:
    app.kubernetes.io/name: nginx-gateway
  ports:
    - name: metrics
      port: 10254
      targetPort: 10254
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-gateway-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - nginx-gateway
  selector:
    matchLabels:
      metrics: enabled
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics

